import { Footer } from "@/components/ui/footer/footer";
import { Providers } from "@/providers/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="">
            <div className="">{children}</div>

            <div className="mt-40">
              <Footer />
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
